language: python
script:
  - pytest tests/*.py

install:
  - pip install travis-sphinx

script:
    - travis-sphinx build

after_success:
    - travis-sphinx deploy


notifications:
  slack: dunescience:HnUdVUQSSlhocorG8poRdXhm
